### PR TITLE
Update requires

### PR DESCRIPTION
**Pull request by jaap3**
Noticed the requires line in `usage.md` and `README.md` was inconsistent with how it was specified elsewhere (`customizing.md` and `index.md`).

### CODE REVIEW

**Comment by jaap3** [comment]
Didn't see this before creating this PR: #921 is an issue about the inconsistency in the docs

**Comment by RonnyPfannschmidt** [comment]
lets use the examples from https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html as base

for safety the backend needs to be added, wheel is auto-added these days by setuptools internals

**Review by RonnyPfannschmidt — APPROVED** [review]
Lovely, thanks 👍

**Comment by jaap3** [comment]
@RonnyPfannschmidt I've updated the PR. Not 100% sure I understood what you meant so I hope it's alright :)

There's still a small inconsistency with the minimum setuptools required. The examples now all say >=64, but the text and the setuptools integration check say >=61.

**Pull request merged**
