### PR TITLE
Add command to print next version

### PR DESCRIPTION
**Pull request by jacobolofsson**
Fix for #222

Adds a "increment" version scheme, that guesses the next version, and
does not take distance in to account (no devN postfix).

### CODE REVIEW

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
thanks for trying to tackle this issue,

unfortunately the solution is at the wrong place

the proposed scheme doesn't take into account other version schemes and is not available from other invocations/scemes in a practical manner

instead of creating a new version scheme, the returned version should drop the dev/local part in some way (in case of a clean workdir that is)

ideally this should be available as setup command as well as a opt-in for the get_version call (which in turn can be argument-ed with a env var later on)

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback

**Comment by jacobolofsson** [comment]
The next time I have some free time on my hands I might take a crack at this again, but ill reopen it when(if?) I get there.

**Comment by RonnyPfannschmidt** [comment]
@jacobolofsson thanks for the update

**Pull request closed without merging**
