### PR TITLE
Support git archives

### PR DESCRIPTION
**Pull request by Changaco**
Implements #65.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
rejecting as its broken exactly like i explained in #65

**Comment by Changaco** [comment]
Not working for untagged commits is not the same thing as being broken.

**Comment by RonnyPfannschmidt** [comment]
unless it works for pip install towards a master branch its problematic to begin with and all tags can just as easily be released

**Comment by Changaco** [comment]
Supporting git archives of tagged commits is useful (see https://github.com/Changaco/python-libarchive-c/issues/23). How is it better to have no support at all instead of partial support?

**Comment by RonnyPfannschmidt** [comment]
releases can just be released, but having some archvies work and some archvies not is undesirable
in particular since some of the hash urls will work and some not

if all it can ever do is work with whats supposed to be official releases, just use actual releases, those install faster, are more reliable and certain to have all metadata

even the project you references talked about just using the pypi releases

and what i really really really don't want to cause a project is solving the guaranteed to come up support request to make it work for all archives instead of some

inconsistent support for archives is bound to create suffering for downstreams - providing consistent experience is very important

**Comment by Changaco** [comment]
The user didn't want to use PyPI releases, that's why I went looking for a way to include version numbers into GitHub releases. If we can't integrate support for that in `setuptools_scm` then I'll have to stick with [version.py](https://github.com/Changaco/version.py/), and/or fork `setuptools_scm` so my work here doesn't go to waste.

**Comment by RonnyPfannschmidt** [comment]
due to how setuptools_scm works, you can just create a plugins that does the same,
all you need to do is register a .git_archival.txt as entrypoint in that plugin,
and then have the plugin depend on setuptools_scm and use both as setup_requires

that way you can use the functionality for tagged archives,and still have the rest work normally

**Comment by RonnyPfannschmidt** [comment]
i#d even be willing to document such a plugin as additional usage vector including a description of why its not in setuptools_scm itself

**Comment by Changaco** [comment]
https://pypi.python.org/pypi/setuptools_scm_git_archive

**Comment by RonnyPfannschmidt** [comment]
@Changaco well done, any suggestion how to refer to it from the docs, i#m thinking of a little reorg

**Pull request closed without merging**
