### PR TITLE
Rename license_file to license_files

### PR DESCRIPTION
**Pull request by jelmer**
Rename license_file to license_files

This fixes a deprecation warning.

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
thanks!

**Comment by RonnyPfannschmidt** [comment]
@jelmer can you run pre-commit for this one, it seems like a msisconfig is currently preventing auto-push

@asottile are there any docs on how to alow pre-commit to push, i believe i missed some setting and/or a pypa policy is preventing it atm

**Comment by RonnyPfannschmidt** [comment]
nm, found it

**Comment by RonnyPfannschmidt** [comment]
or not :/

**Comment by asottile** [comment]
@RonnyPfannschmidt hmmm the only think I could think of is if OP unchecked the "allow maintainers to push" box (which is what the run says too)

**Comment by jelmer** [comment]
@RonnyPfannschmidt done, all green now :)

**Comment by RonnyPfannschmidt** [comment]
@asottile i believe we just found a bug in setup-cfg-format related to a setuptools change

I can't promise to get back to that this week

**Comment by asottile** [comment]
there's a bunch of dupes in the tracker, it's currently the intended behavior

**Comment by RonnyPfannschmidt** [comment]
@asottile the current intended behaviour seems to be at odds with the deprecation in setuptools then, should there be some gating wrt supported versions?

**Comment by asottile** [comment]
I'm going to let you read the issues first rather than rehashing everything here 👍

**Comment by RonnyPfannschmidt** [comment]
@asottile oh yikes, support timelines crossing the toml warzone - would i be able to persuade you with a pr fix where it skips adding license-file if license-files is set? and/or a cli option for the hook?

**Comment by asottile** [comment]
perhaps something like that -- though as written that'd break something like `babi-grammars` which uses `license_files` for vendored things.  perhaps if it's _exactly_ `license-files = {the same thing it would set license_file to currently}` then that's fine

**Comment by RonnyPfannschmidt** [comment]
@asottile so my intent would be to opt out of setting license-file if its missing only if license-files is set

**Comment by asottile** [comment]
yeah I think the reasonable behaviour is:

1. if `license_files` is set to the same value of what `setup-cfg-fmt` today would set `license_file` to -- do nothing
2. otherwise do the current behaviour

at a future date when the setuptools version where license-files works is old enough then change the behaviour to set-add the license file to `license_files` but I can't do that now without breaking old stuff

**Comment by RonnyPfannschmidt** [comment]
with the migration to pyproject.toml this became obsolete before i got back to it

thanks for working on it

at least we got https://github.com/asottile/setup-cfg-fmt/pull/166 out of it

**Pull request closed without merging**
