### PR TITLE
Respect git's export-ignore for building the sdist.

### LINKED ISSUE #185: support git's export-ignore
`git archive` reads the `export-ignore` gitattribute (https://git-scm.com/docs/gitattributes#_creating_an_archive) which allows marking some files as NOT packaged into the archive.  It would be nice if setuptools_scm did the same for the sdist.

Typical use cases would be to remove CI scripts.

Unfortunately AFAICT there is no way to ask git for the files it would archive short of actually running git archive and examining the resulting tarball.  OTOH it appears that such a step is much faster than the sdist build itself, so perhaps that remains an acceptable approach?

### PR DESCRIPTION
**Pull request by anntzer**
Implemented by replacing the call to 'git ls-files' to '$sys.executable
-msetuptools_scm.git' with the module parsing the output of 'git
archive' as a tar file.

Fixes #185.  Actually that was easier to do than expected...

I haven't edited the README because I don't think it even explicitly mentions right now that it'll sdist exactly all files tracked by the VCS (it's only implicit in the doc for `setuptools_scm.files_command`), so I don't have a good place to introduce the new piece of info...

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
thats a neat trick, lovely 👍

**Comment by RonnyPfannschmidt** [comment]
i jsut crosschecked, the linting failures are unrelated and came in with a update of flake8

the python2.6 failure is unfortunate - im pondering wheter we should finally drop python2.6 here given that older releases support it fine

@jaraco i'd appreciate your input on the lower python version support

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by anntzer** [comment]
I guess it's not too hard to switch to Popen but I would appreciate if you could pick up that work (Py2.6 is veeeeery far away for me...).  Feel free to push to my branch.

**Comment by RonnyPfannschmidt** [comment]
@jaraco lovely chain, thanks for just stepping in and implementing it 👍

**Comment by RonnyPfannschmidt** [comment]
oh drats, i just noted the errors on windows, its not clear how to fix those over there
i#ll try to take a closer look in the afternoon

**Comment by jaraco** [comment]
> i'd appreciate your input on the lower python version support

I'm happy to drop support for Python 2.6, though I still would prefer this implementation that happens to run on Python 2.6.

**Comment by RonnyPfannschmidt** [comment]
tests still fail on windows :/

**Comment by anntzer** [comment]
Fixed now.

**Comment by RonnyPfannschmidt** [comment]
well done, thanks

**Pull request merged**
