### PR TITLE
empty

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
Sorry, I meant to open this in my own repo but GitHub was too helpful.  Anyways, I'm exploring an apparent regression related to the release of setuptools 60.9.1 as far as I know right now where I started getting a local version suddenly despite having `no-local-version` in `pyproject.toml`.  Anyways, if I get good details I'll share them.

```toml
[tool.setuptools_scm]
local_scheme = "no-local-version"
```

**Comment by webknjaz** [comment]
@altendky did you figure it out? I'm seeing this too!

**Comment by webknjaz** [comment]
> @altendky did you figure it out? I'm seeing this too!

*UPD*: It was a combination of newer setuptools (v69) and older setuptools-scm (v7). Upgrading it to v8 fixed the problem.

**Comment by altendky** [comment]
I think this was how I addressed it.  https://github.com/Chia-Network/chia-blockchain/commit/ffe4e7ca3772828983873bd27527c662f0016a7b  We had some setuptools-scm config in `setup.py` and some in `pyproject.toml`.  I moved it to just `pyproject.toml`.

**Comment by webknjaz** [comment]
Yeah, I figured. I think it was triggered by me bumping just this plugin in the lockfile and not setuptools itself. Good to document that this may be happening, though..

**Pull request closed without merging**
