### PR TITLE
Fix Missing importlib_metadata in <=3.7

### LINKED ISSUE #718: setuptools_scm 7.0.0 fails with Python 3.7
When using `setuptools_scm` in a CI pipeline to install a package I'm getting:

```
ModuleNotFoundError: No module named 'importlib.metadata'
```
compare https://github.com/audeering/audonnx/runs/6985662108?check_suite_focus=true

which is a common `importlib` bug described for example at https://github.com/newville/asteval/issues/93

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #718

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
this looks like the fix,

i need to create a way to test this type of possible failure

**Comment by kojiromike** [comment]
@RonnyPfannschmidt I have a local dockerfile that I just finished testing this fix in; however, it will take me a little while to figure out why the 3.7 tests in this repo didn't already catch the error.

**Comment by kojiromike** [comment]
Pushing a hypothetical change that might fail in 3.7 to show if tests work.

**Comment by kojiromike** [comment]
@RonnyPfannschmidt I think this is ready for testing now. It will fail in <3.8, correctly, if you remove the conditional requirement. I didn't want to spam this PR too much, but you can see that failure over here: https://github.com/kojiromike/setuptools_scm/actions/runs/2536366008 (I canceled the workflow after the necessary tests ran.)

**Review by cesarlr — APPROVED** [review]

**Comment by kojiromike** [comment]
Still no good on the testing front. I guess a PEP517 build will use the pyproject requirements, including importlib_metadata and thus passing, even in python 3.7. But it seems a non-PEP517 build using pip or `setup.py` will not install the setup dependencies before trying to run `setup.py`, where it all falls apart.

**Comment by kojiromike** [comment]
I've put things back to just the fix, as I'm unable to find a way to automatically test right now.

**Review by cesarlr — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
Lovely, thanks for testing out the details, if you add a changelog entry i can directly go for merge +release after dinner

**Comment by kojiromike** [comment]
@RonnyPfannschmidt done, Genieße dein Abendessen

**Pull request merged**
