### PR TITLE
Revert "git: DEFAULT_DESCRIBE: add --first-parent"

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
Reverts pypa/setuptools_scm#346

as  it turns out i missed how badly this breaks workflows of people

CC @blueyed

### CODE REVIEW

**Comment by blueyed** [comment]
Fair enough.

But JFI: it is rather uncommon to merge tags (as pytest does it) - normally you have the tag on the branch itself.
`--first-parent` then ensures that you do not use tags from release/hotfix branches then (where the release tag is on the release branch).
I assume pytest also wants to use `--first-parent` once a more common release / branch workflow is used.

**Comment by RonnyPfannschmidt** [comment]
@blueyed as far as i  understood, it breaks the well used git flow style (which fits the branch names in #395  )

**Comment by blueyed** [comment]
@RonnyPfannschmidt seems not related (https://github.com/pypa/setuptools_scm/issues/395#issuecomment-575992836).

Re git-flow: tags are on master there (https://danielkummer.github.io/git-flow-cheatsheet/ - in case that's the one you mean)

**Comment by blueyed** [comment]
I agree though in general that it should have at least been mentioned in the changelog.. ;)
And I can see that it affects/breaks uncommon flows, of course.
So go ahead with reverting I'd say - maybe there is some heuristic that could be used however, given that previously it did not work as expected with the "git-flow style".

**Comment by RonnyPfannschmidt** [comment]
thanks for putting in some extra refs/ding the extra research

**Pull request merged**
