### PR TITLE
Fix __main__ imports.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
A simple test added as well.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
... travis is not running the proper test for some reason; fixing this...

**Comment by mcmtroffaes** [comment]
Travis issue seems fixed now.

**Comment by RonnyPfannschmidt** [comment]
Good find

**Comment by mcmtroffaes** [comment]
Thanks for the quick merge!

**Comment by RonnyPfannschmidt** [comment]
i hope i can release this weekend as well

**Pull request merged**
