### PR TITLE
Rename the project to setuptools-scm

### LINKED ISSUE #1067: Rename the project to setuptools-scm
As I pointed out in [this message](https://github.com/pypa/setuptools_scm/commit/1e224324604f910d20ef625e18a29b254305417f#r145320262), it seems that this project is unclear on what its name is. Historically, the name has been `setuptools_scm`, but with the 8.0 release and the move to pyproject.toml, the project renamed to `setuptools-scm`, but kept the name `setuptools_scm` in other places.

Incidentally, the project also seems to have had `setuptools-scm` as the indicated name (pre-normalized) in the wheels for versions prior to 8.0 as well. It'd be interesting to know why that is.

I'm not particularly interested in what the name of the project is, but I am interested in being consistent about it and avoiding being capriciously inconsistent just because the normalization allows it.

### PR DESCRIPTION
**Pull request by jaraco**
Indicates the rename occurred in the v8 release, since that's when the name was changed in the source metadata.

After merging this, we'll rename the project in GitHub to match.

Closes #1067

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
awesome, thanks :+1:
 this looks complete - i'll prepare to merge later today when we can also rename the repository in github to match the normalization

**Comment by shenxianpeng** [comment]
The repository `setuptools_scm` hasn't been renamed yet.

**Comment by jaraco** [comment]
> The repository `setuptools_scm` hasn't been renamed yet.

Thanks for mentioning this. I just renamed it.

**Review by Pandastacos — COMMENTED** [review]
[Evolution_36_mail.pdf](https://github.com/user-attachments/files/17531501/Evolution_36_mail.pdf)

**Comment by Pandastacos** [comment]
oops
[Terminal Saved Output.txt](https://github.com/user-attachments/files/17531503/Terminal.Saved.Output.txt)

**Pull request merged**
