### PR TITLE
cleanups + bugfixes

### LINKED ISSUE #953: pyproject.toml does not contain a tool.setuptools_scm section
I'm packaging various Python projects for OpenIndiana.  The packaging (and especially testing) is done in real environment with possibly many unrelated packages installed to make sure the packaged project works properly once it is installed.

When I try to work with a project that does not use `setuptools_scm` and `setuptools_scm` is installed then I see this warning:
```
[10/08/23 10:00:26] WARNING  pyproject.toml does not contain a tool.setuptools_scm section                                  setuptools.py:119
```
The warning is seen in many logs, including testing log.  This causes a problem to us because it raises errors when we compare test logs between test runs.  Yes, we could add a special rule to our testing logic to filter out this warning, but since this is a regression from `setuptools_scm==7.1.0` then I'd prefer to see it fixed/changed at the `setuptools_scm` side.

Possible solution would be to change `log.warning(e)` to `log.debug(e)` in the [setuptools.py file](https://github.com/pypa/setuptools_scm/blob/v8.0.4/src/setuptools_scm/_integration/setuptools.py#L119).  If that's not possible or desirable then what about to implement some way how to silence the warning using an environment variable?

Thank you.

### LINKED ISSUE #957: Timeout with version 8.0.4 (git describe)
This issue is similar to https://github.com/pypa/setuptools_scm/issues/913

But this time with the command `git describe ... `

```
* Creating venv isolated environment...

* Installing packages in isolated environment... (setuptools>=45, setuptools_scm[toml]>=6.2)

* Getting build dependencies for wheel...

Traceback (most recent call last):

  File "D:\GitHub-Runner\package-repo\.tox\release\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>

    main()

  File "D:\GitHub-Runner\package-repo\.tox\release\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main

    json_out['return_val'] = hook(**hook_input['kwargs'])

  File "D:\GitHub-Runner\package-repo\.tox\release\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel

    return hook(config_settings)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel

    return self._get_build_requires(config_settings, requirements=['wheel'])

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires

    self.run_setup()

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup

    exec(code, locals())

  File "<string>", line 1, in <module>

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\__init__.py", line 103, in setup

    return distutils.core.setup(**attrs)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup

    _setup_distribution = dist = klass(attrs)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\dist.py", line 303, in __init__

    _Distribution.__init__(self, dist_attrs)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__

    self.finalize_options()

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools\dist.py", line 680, in finalize_options

    ep(self)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_integration\setuptools.py", line 121, in infer_version

    _assign_version(dist, config)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_integration\setuptools.py", line 53, in _assign_version

    maybe_version = _get_version(config, force_write_version_files=True)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_get_version_impl.py", line 93, in _get_version

    parsed_version = parse_version(config)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_get_version_impl.py", line 56, in parse_version

    or parse_scm_version(config)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_get_version_impl.py", line 35, in parse_scm_version

    return _entrypoints.version_from_entrypoint(

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_entrypoints.py", line 55, in version_from_entrypoint

    maybe_version: version.ScmVersion | None = fn(root, config=config)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\git.py", line 211, in parse

    return _git_parse_inner(

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\git.py", line 255, in _git_parse_inner

    version = version_from_describe(wd, config, describe_command)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\git.py", line 237, in version_from_describe

    describe_res = wd.default_describe()

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\git.py", line 157, in default_describe

    return run_git(DEFAULT_DESCRIBE[1:], self.path)

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\git.py", line 58, in run_git

    return _run(

  File "C:\Windows\Temp\build-env-cae0l3kt\lib\site-packages\setuptools_scm\_run_cmd.py", line 144, in run

    res = subprocess.run(

  File "D:\GitHub-Runner\_tool\Python\3.10.11\x64\lib\subprocess.py", line 505, in run

    stdout, stderr = process.communicate(input, timeout=timeout)

  File "D:\GitHub-Runner\_tool\Python\3.10.11\x64\lib\subprocess.py", line 1154, in communicate

    stdout, stderr = self._communicate(input, endtime, timeout)

  File "D:\GitHub-Runner\_tool\Python\3.10.11\x64\lib\subprocess.py", line 1546, in _communicate

    raise TimeoutExpired(self.args, orig_timeout)

subprocess.TimeoutExpired: Command '['git', '--git-dir', 'C:\\Windows\\Temp\\devpi-hpq_8ttl\\.git', 'describe', '--dirty', '--tags', '--long', '--match', '*[0-9]*']' timed out after 20 seconds
```

### LINKED ISSUE #960: setuptools_scm does not create a version file after 8.0.0 release
pyproject.toml
```
[project]
name = "project"
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "project/version.py". # <- before 8.0.0 was write_to
version_scheme = "calver-by-date"
```

```
❯ SETUPTOOLS_SCM_DEBUG=1 python -m setuptools_scm
[10/18/23 15:06:37] DEBUG    dist name: project                                                                                            _overrides.py:40
                    DEBUG    check absolute root=. relative_to=/Users/mogost/work/project/pyproject.toml                       _config.py:60
                    DEBUG    file /Users/mogost/work/project/pyproject.toml                                                    _config.py:79
                    DEBUG    version_from_ep setuptools_scm.parse_scm in /Users/mogost/work/project                       _entrypoints.py:52
                    DEBUG    looking for ep setuptools_scm.parse_scm in /Users/mogost/work/project                            discover.py:59
                    DEBUG    found ep EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') in       discover.py:67
                             /Users/mogost/work/project                                                                                     
                    DEBUG    at .                                                                                                         _run_cmd.py:143
                                 $ git version                                                                                                           
                    DEBUG    out:                                                                                                         _run_cmd.py:163
                                 git version 2.39.3 (Apple Git-145)                                                                                      
                    DEBUG    at /Users/mogost/work/project                                                                   _run_cmd.py:143
                                 $ git --git-dir /Users/mogost/work/project/.git rev-parse --show-prefix                                    
                    DEBUG    real root /Users/mogost/work/project                                                                  git.py:87
                    DEBUG    at /Users/mogost/work/project                                                                   _run_cmd.py:143
                                 $ git --git-dir /Users/mogost/work/project/.git describe --dirty --tags --long --match                     
                             "*[0-9]*"                                                                                                                   
                    DEBUG    out:                                                                                                         _run_cmd.py:163
                                 v23.9.13.1-232-g5a2e09102c-dirty                                                                                        
                    DEBUG    tag v23.9.13.1                                                                                                 version.py:91
                    DEBUG    'v23.9.13.1' re.compile('^(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$') <re.Match    version.py:54
                             object; span=(0, 10), match='v23.9.13.1'>                                                                                   
                    DEBUG    key 1 data {'version': 'v23.9.13.1'}, ('v23.9.13.1',), 'v23.9.13.1'                                            version.py:55
                    DEBUG    tag 'v23.9.13.1' parsed to {'version': 'v23.9.13.1', 'prefix': '', 'suffix': ''}                               version.py:64
                    DEBUG    version pre parse v23.9.13.1                                                                                   version.py:99
                    DEBUG    version=<Version('23.9.13.1')>                                                                                version.py:105
                    INFO     version v23.9.13.1 -> 23.9.13.1                                                                               version.py:211
                    DEBUG    at /Users/mogost/work/project                                                                   _run_cmd.py:143
                                 $ git --git-dir /Users/mogost/work/project/.git rev-parse --abbrev-ref HEAD                                
                    DEBUG    out:                                                                                                         _run_cmd.py:163
                                 dependabot/pip/develop/black-d--23.10.0                                                                                 
                    DEBUG    at /Users/mogost/work/project                                                                   _run_cmd.py:143
                                 $ git --git-dir /Users/mogost/work/project/.git -c log.showSignature=false log -n 1 HEAD                   
                             --format=%cI                                                                                                                
                    DEBUG    out:                                                                                                         _run_cmd.py:163
                                 2023-10-18T13:47:20+06:00                                                                                               
                    DEBUG    EntryPoint(name='.git', value='setuptools_scm.git:parse', group='setuptools_scm.parse_scm') found         _entrypoints.py:56
                             <ScmVersion 23.9.13.1 dist=232 node=g5a2e09102c dirty=True                                                                  
                             branch=dependabot/pip/develop/black-d--23.10.0>                                                                             
                    DEBUG    scm version <ScmVersion 23.9.13.1 dist=232 node=g5a2e09102c dirty=True                                        version.py:426
                             branch=dependabot/pip/develop/black-d--23.10.0>                                                                             
                    DEBUG    config Configuration(relative_to='/Users/mogost/work/project/pyproject.toml', root='.',          version.py:427
                             version_scheme='calver-by-date', local_scheme='node-and-date',                                                              
                             tag_regex=re.compile('^(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$'),                             
                             parentdir_prefix_version=None, fallback_version=None, fallback_root='.', write_to=None,                                     
                             write_to_template=None, version_file='project/version.py', version_file_template=None, parse=None,                            
                             git_describe_command=None, dist_name='project', version_cls=<class 'packaging.version.Version'>,                              
                             search_parent_directories=False, parent=PosixPath('/Users/mogost/work/project'))                               
                    DEBUG    ep found: calver-by-date                                                                                  _entrypoints.py:71
[10/18/23 15:06:38] DEBUG    version 23.10.18.0.dev232                                                                                     version.py:434
                    DEBUG    ep found: node-and-date                                                                                   _entrypoints.py:71
                    DEBUG    local_version +g5a2e09102c.d20231018                                                                          version.py:439
23.10.18.0.dev232+g5a2e09102c.d20231018

```

```
❯ ls -la project/version.py
ls: project/version.py: No such file or directory
```

### LINKED ISSUE #966: Type in config doc
Hi

Looks like there is a typo with `version_file_template` in the [`config.md`](https://github.com/pypa/setuptools_scm/blob/8bc891665d65ae5b4e86357862d1b9039a6a741b/docs/config.md?plain=1#L32C26-L32C26).
Also the doc does not mention the `version_tuple` keyword argument. How about something like this ?
```diff
diff --git a/docs/config.md b/docs/config.md
index 0acdf6f..f187ae4 100644
--- a/docs/config.md
+++ b/docs/config.md
@@ -29,9 +29,9 @@ Callables or other Python objects have to be passed in `setup.py` (via the `use_
         Only files with `.py` and `.txt` extensions have builtin templates,
         for other file types it is necessary to provide `write_to_template`.

-`version_file_template_template: str | None = None`
+`version_file_template: str | None = None`
 :   A new-style format string that is given the current version as
-    the `version` keyword argument for formatting.
+    the `version` and `version_tuple` keyword arguments for formatting.

 `write_to: Pathlike[str] | Path | None = None`
 :  (deprecated) legacy option to create a version file relative to the scm root
```

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
* closes #957 
* closes #966
* closes #960 
* closes #953

### CODE REVIEW

**Comment by eachimei** [comment]
@RonnyPfannschmidt please kindly note that in git.py in `run_git` there's currently a default value to `timeout: int = 20`. As a result, the changes of `BROKEN_TIMEOUT` (env var override) won't take effect.
Also, in `fetch_shallow()` a timeout value of 240 is passed into `run_git` call so if the user overrides the env-var it won't impact this subprocess call.

**Comment by RonnyPfannschmidt** [comment]
thanks for the note, - i completely missed that detail -  i'll integrate the none pass-over there as well

**Comment by RonnyPfannschmidt** [comment]
i'll leave the timeout i fetch shallow for now as its intentional as is and the delay should work as intended for now

its not used by default and i'll start to recommend people prepare unshallow in ci instead of adding the setting to setuptools_scm

**Comment by eachimei** [comment]
alright, sounds good 👍

**Pull request merged**
