### PR TITLE
cleanup pyproject loading and allow cli relative roots to be specified

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this also tries to address concerns by @qubidt in #691 / #702

please take a look if this resolves the issue

### CODE REVIEW

**Review by baodrate — APPROVED** [review]
looks good! passes all the cases I can come up with

**Comment by RonnyPfannschmidt** [comment]
@qubidt can you share those, I'd like to have them part of the testsuite

**Comment by baodrate** [comment]
I only wrote a few, you can see them in the PR I made against the original #702:

https://github.com/GDYendell/setuptools_scm/pull/1/files#diff-6f46d110c3d6f83624aca4044339075d63fdb10acd2b1f0c2ade98204c0a34ec

Of which one (`test_repo_cmdline_root_relative_cwd` I *think*) fails against the current master but passes with this PR. If you want to add them to the feel free to copy them. Don't go out of your way to merge my commit or anything, lol

most of the other cases I was referring to were just manual testing I did w/ variations of `.`/`..`/relative/linked paths for `-r` and `-c`. Nothing particularly interesting or useful

**Comment by RonnyPfannschmidt** [comment]
thanks for the update, time for merge and release then

**Pull request merged**
