### PR TITLE
File finders spec compliance, work in subdirectories too

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
thanks for adapting the tests, since there is no fix yet it would hep to keep those xfail for now

**Comment by sbidoul** [comment]
So while I was in this rabbit hole, I went to the bottom of it :)

So this is now
- a fix for #251 
- a fix for #248 
- a refactoring of the file finders so hg and git use the same algorithm (and the same test suite)

**Comment by RonnyPfannschmidt** [comment]
fabulous work as is, i'm happy to merge :+1:
im currently on a vacation but i'll try to get this released soon as it is quite an enhancement

**Comment by sbidoul** [comment]
@RonnyPfannschmidt Thanks for the review and merge, and the kind words.

Perhaps releasing a beta 2.1 first would be best? Although I've been very careful and tried to think about many tests, there is still a slight chance that the new algorithm would exclude some files that were included by the previous version. Not sure how `setup_requires` works with beta releases though.

Enjoy the holidays.

**Comment by RonnyPfannschmidt** [comment]
beta releases wont work for setup_requires in a discoverable way , in my experience its better to pull a release if a major issue is found rather than having a beta that nobody uses

**Comment by sbidoul** [comment]
ok, go for a release then

We have pretty advanced use cases in the Odoo community so if anything goes wrong, there is a fair chance it will show up there first (and I did test these quite a lot already).

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Pull request merged**
