### PR TITLE
Allow setting a fallback version in case everything else fails.

### PR DESCRIPTION
**Pull request by anntzer**
Revival of #308, but with tests now :)
Initially discussed at https://github.com/pypa/setuptools_scm/issues/198#issuecomment-418666112.

### CODE REVIEW

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
looks good :+1: thank for revising and completing it

 please add it to the change-log as well

**Comment by anntzer** [comment]
should that go under a `next` heading in the changelog?

edit: done

**Comment by anntzer** [comment]
good to go?

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
thanks for the ping, nicely done, for personal reasons i might not make it to a release myself until next weekend

**Comment by anntzer** [comment]
No hurries, thanks for taking care of this.

**Pull request merged**
