### PR TITLE
hg: use same logic as git for finding latest tagged commit

### PR DESCRIPTION
**Pull request by avirshup**
This is a fix for #229

### CODE REVIEW

**Comment by avirshup** [comment]
This PR ignores hg tags that don't contain a '.' in them (similarly to the way git.py uses `git describe`).

I've created a couple new helper functions in `hg.py` to do this -
 - `get_graph_distance` for computing the distance between two revisions in mercurial, and
 - `get_latest_normalizable_tag`, for returning the latest "version-like" hg tag. Right now, it just inelegantly filters for the presence of '.' in the tag.  But it will likely be rewritten by a more general test in the fix for #235.

**Comment by RonnyPfannschmidt** [comment]
sorry for the delay, i have been on travel and didnt get to sorting it before, i plan to sort the backlog on setuptools_scm until the weekend, thanks for the patience

**Comment by RonnyPfannschmidt** [comment]
thanks :+1:

**Comment by avirshup** [comment]
Thanks - and no worries whatsoever about the timing, open source maintainers deserve vacations too :)

**Comment by RonnyPfannschmidt** [comment]
i plan to do a release with support for branches added and support for ancient broken setuptools dropped, please take a look

**Pull request merged**
